export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CLINIC_ADMIN = 'CLINIC_ADMIN',
  RECEPTIONIST = 'RECEPTIONIST',
  DENTIST = 'DENTIST',
  HYGIENIST = 'HYGIENIST',
  DENTAL_ASSISTANT = 'DENTAL_ASSISTANT',
  PATIENT = 'PATIENT',
}
